services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # comunicação
      - "15672:15672"  # dashboard web
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  backend:
    build: ./backend/.
    container_name: golang-backend
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M


  middleware:
    build: ./middleware/.
    container_name: golang-middleware
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
